language: java
jdk:
  - oraclejdk8

jobs:
  include:
    - stage: check
      script: ./gradlew tasks
    - stage: build
      script: ./gradlew build
    - stage: archives
      script: ./gradlew archive

env:
  global:
    TERM=dumb
