language: java
jdk:
  - oraclejdk8

jobs:
  include:
    stage: setup
    script: ./gradlew build
    stage: test
    script: ./gradlew test
    stage: archives
    script: ./gradlew archive

env:
  global:
    TERM=dumb
